spring.application.name=volunteerplatform

spring.datasource.url=jdbc:postgresql://localhost:5432/volunteer_db
spring.datasource.username=postgres
spring.datasource.password=2022
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.security=DEBUG

# This is a secure, 64-byte, Base64-encoded secret key suitable for HS512 algorithm
jwt.secret=N2Q4ZDY4NTY2NTc4NjE2ZDY5NjM2YjY0NzM2NTcyNzM2MTcyNjE2ZTc0NzU3MjY1NzI2MTZlNjQ2NTcyNzM2MTcyNjE2ZTc0NzU3MjY1NzI2MTZlNjQ2NTcyNzM2MTcyNjE2ZTc0NzU3MjY1NzI2MTZlNjQ2NTcyNzM2MTcyNjE2ZTc0NzU3MjY1NzI2MTZlNjQ2NTcyNzM2MTcyNjE2ZTc0NzU3MjY1NzI2MTZlNjQ2NTcyNzM2MTcyNjE2ZTc0NzU3MjY1NzI2MTZlNjQ2NTcyNzM2MTcyNjE2ZTc0NzU3MjY1NzI2MTZlNjQ2NTcyNzM2MTcyNjE2ZTc0NzU3MjY1NzI2MTZlNjQ2NTcyNzM2MTcyNjE2ZTc0NzU3MjY1NzI2MTZlNjQ2NTcyNzM2MTcyNjE2ZTc0NzU3MjY1NzI2MTZlNjQ2NTcyNzM2MTcyNjE2ZTc0NzU3MjY1NzI2MTZlNjQ2NTcyNzM2MTcyNjE2ZTc0NzU3MjY1NzI2MTZlNjQ2NTcyNzM2MTcyNjE2ZTc0NzU3MjY1NzI2MTZlNjQ2NTcyNzM2MTcyNjE2ZTc0NzU3MjY1NzI2MTZlNjQ2NTcyNzM2MTcyNjE2ZTc0NzU3MjY1==
